name: Deploy Next.js site to GitHub Pages

on:
  push:
    branches: ["main"]  # Cambia esto si deseas que se dispare en otra rama

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Build with Next.js
        run: npm run build
      - name: Export Next.js site
        run: npm run export  # Asegúrate de tener este script en package.json
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out  # Asegúrate de que esta ruta sea correcta
          publish_branch: gh-pages  # Cambia esto si deseas usar otra rama
